# default model config does not override anything
default: {}

# just an example of how to use these configs
alt_prior:
  model_kwargs:
    intervention_prior:
      type: normal
      scale: 0.15
  featurize_kwargs:
    drop_npi_filter:
     - query: Retail Closed
       type:  equals
     - query: Outdoor
       type: includes

npi_set_1:
  model_kwargs: {}
  featurize_kwargs:
    drop_npi_filter:
     - query: Retail Closed
       type:  equals
     - query: Outdoor
       type: includes

npi_set_2:
  model_kwargs: {}
  featurize_kwargs:
    drop_npi_filter:
     - query: Retail Closed
       type:  equals
     - query: Outdoor
       type: includes
     - query: Stay at Home Order
       type: equals
     - query: Mask
       type: includes

npi_set_3:
  model_kwargs: {}
  featurize_kwargs:
    drop_npi_filter:
     - query: Retail Closed
       type:  equals
     - query: Outdoor
       type: includes
     - query: Stay at Home Order
       type: equals
     - query: Mask
       type: includes
     - query: Leisure
       type: includes

npi_set_4:
  model_kwargs: {}
  featurize_kwargs:
    drop_npi_filter:
     - query: Retail Closed
       type:  equals
     - query: Outdoor
       type: includes
     - query: Stay at Home Order
       type: equals
     - query: Mask
       type: includes
     - query: Leisure
       type: includes
     - query: Childcare
       type: includes

npi_set_5:
  model_kwargs: {}
  featurize_kwargs:
    drop_npi_filter:
     - query: Retail Closed
       type:  equals
     - query: Outdoor
       type: includes
     - query: Stay at Home Order
       type: equals
     - query: Mask
       type: includes
     - query: Leisure
       type: includes
     - query: Childcare
       type: includes
     - query: Universities
       type: includes

npi_set_6:
  model_kwargs: {}
  featurize_kwargs:
    drop_npi_filter:
     - query: Retail Closed
       type:  equals
     - query: Outdoor
       type: includes
     - query: Stay at Home Order
       type: equals
     - query: Mask
       type: includes
     - query: Leisure
       type: includes
     - query: Childcare
       type: includes
     - query: Universities
       type: includes
     - query: Some Face-to-Face
       type: includes

npi_set_7:
  model_kwargs: {}
  featurize_kwargs:
    drop_npi_filter:
     - query: Retail Closed
       type:  equals
     - query: Outdoor
       type: includes
     - query: Stay at Home Order
       type: equals
     - query: Mask
       type: includes
     - query: Leisure
       type: includes
     - query: Childcare
       type: includes
     - query: Universities
       type: includes
     - query: Extra
       type: includes

npi_set_8:
  model_kwargs: {}
  featurize_kwargs:
    drop_npi_filter:
     - query: Retail Closed
       type:  equals
     - query: Outdoor
       type: includes
     - query: Stay at Home Order
       type: equals
     - query: Mask
       type: includes
     - query: Leisure
       type: includes
     - query: Childcare
       type: includes
     - query: Universities
       type: includes
     - query: Extra
       type: includes
     - query: Curfew
       type: includes


# need to run from here
npi_set_9:
  model_kwargs: {}
  featurize_kwargs:
    drop_npi_filter:
     - query: Retail Closed
       type:  equals
     - query: Outdoor
       type: includes
     - query: Stay at Home Order
       type: equals
     - query: Mask
       type: includes
     - query: Leisure
       type: includes
     - query: Childcare
       type: includes
     - query: Universities
       type: includes
     - query: Extra
       type: includes
     - query: Curfew
       type: includes
     - query: Gathering
       type: includes

npi_set_10:
  model_kwargs: {}
  featurize_kwargs:
    drop_npi_filter:
     - query: Retail Closed
       type:  equals

npi_set_11:
  model_kwargs: {}
  featurize_kwargs:
    drop_npi_filter:
     - query: Retail Closed
       type:  equals
     - query: Extra
       type:  includes

npi_set_12:
  model_kwargs: {}
  featurize_kwargs:
    drop_npi_filter:
     - query: Retail Closed
       type:  equals
    public_gathering_thresholds: [1, 6, 30]
    private_gathering_thresholds: [1, 6, 30]

npi_set_13:
  model_kwargs: {}
  featurize_kwargs:
    drop_npi_filter:
     - query: Retail Closed
       type:  equals
     - query: Outdoor
       type: includes
    public_gathering_thresholds: [1, 6, 30]
    private_gathering_thresholds: [1, 6, 30]

npi_set_14:
  model_kwargs: {}
  featurize_kwargs:
    drop_npi_filter:
     - query: Retail Closed
       type:  equals
    gatherings_aggregation: out_in

npi_set_15:
  model_kwargs: {}
  featurize_kwargs:
    drop_npi_filter:
     - query: Retail Closed
       type:  equals
    gatherings_aggregation: pub_priv

npi_set_16:
  model_kwargs: {}
  featurize_kwargs:
    drop_npi_filter:
     - query: Retail Closed
       type:  equals
    public_gathering_thresholds: [2, 6, 30, 200, 1000]
    private_gathering_thresholds: [2, 6, 30, 200]
    household_upper_limit: 7

keep_both:
  model_kwargs: {}
  featurize_kwargs:
    public_gathering_thresholds: [1, 6, 30, 200]
    private_gathering_thresholds: [1, 6, 30, 200]
    gatherings_aggregation: none
    household_stays_on: True

drop_outdoors:
  model_kwargs: {}
  featurize_kwargs:
    public_gathering_thresholds: [1, 6, 30, 200]
    private_gathering_thresholds: [1, 6, 30, 200]
    gatherings_aggregation: drop_outdoor
    household_stays_on: True

weaker:
  model_kwargs: {}
  featurize_kwargs:
    public_gathering_thresholds: [1, 6, 30, 200]
    private_gathering_thresholds: [1, 6, 30, 200]
    gatherings_aggregation: out_in
    gatherings_aggregation_type: weaker
    household_stays_on: True

stricter:
  model_kwargs: {}
  featurize_kwargs:
    public_gathering_thresholds: [1, 6, 30, 200]
    private_gathering_thresholds: [1, 6, 30, 200]
    gatherings_aggregation: out_in
    gatherings_aggregation_type: stricter
    household_stays_on: True